### ISSUE TITLE
Make GUI rows and columns start from 1

### ISSUE THREAD

**Issue by colton-boi** [DebitCardz/mc-chestui-plus#2]
It seems more sensible that they would start from 1 because there is no "row 0" of a GUI really, I understand you did this because MC starts at slot 0, but you could just change the math slightly. You could also make this an option in GUI creation if you don't want to force it, though I feel it will increase readibility

**Comment by DebitCardz** [comment]
This will absolutely be a breaking change however, I think it's a pretty solid suggestion.
Starting at (1, 1) will be much more intuitive and much less effort to count GUI Slots.
