### ISSUE TITLE
onBottomClick

### ISSUE THREAD

**Issue by jbj338033** [DebitCardz/mc-chestui-plus#29]
how to listen onBottomClick event
(when click player inventory)

**Comment by DebitCardz** [comment]
I don't *think* it's natively possible unfortunately :(

**Comment by DebitCardz** [comment]
Hey! I have great news for you.
In the latest release `1.5.5` this functionality is now supported 😄 

Use it like this,
```kt
gui {
  onPlayerInventoryPickupItem = { player, item, slot -> player.sendMessage("Clicked at $slot") }
}
```
Enjoy!!
